<?php
return [
    'CHABAA_ADMIN_USER' => env('CHABAA_ADMIN_USER'),
    'CHABAA_ADMIN_PASSWORD' => env('CHABAA_ADMIN_PASSWORD'),

    'CHABAA_CONGREGATION_USER' => env('CHABAA_CONGREGATION_USER'),
    'CHABAA_CONGREGATION_PASSWORD' => env('CHABAA_CONGREGATION_PASSWORD'),

    'ICECAST_ADMIN_PASSWORD' => env('ICECAST_ADMIN_PASSWORD'),
    'ICECAST_PORT' => env('ICECAST_PORT'),
    'ICECAST_MOUNT_NAME' => env('ICECAST_MOUNT_NAME'),
];