<?php
return [
    'CHABA_ADMIN_USER' => env('CHABA_ADMIN_USER'),
    'CHABA_ADMIN_PASSWORD' => env('CHABA_ADMIN_PASSWORD'),
    'CHABA_CONGREGATION_USER' => env('CHABA_CONGREGATION_USER'),
    'CHABA_CONGREGATION_PASSWORD' => env('CHABA_CONGREGATION_PASSWORD'),

    'ICECAST_ADMIN_PASSWORD' => env('ICECAST_ADMIN_PASSWORD'),
    'ICECAST_PORT' => env('ICECAST_PORT'),
    'ICECAST_MOUNT_NAME' => env('ICECAST_MOUNT_NAME'),
];